// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/navbar/FullPage.tsx": () => import("../components/mockups/navbar/FullPage.tsx"),
  "./components/mockups/navbar/OldTigersHeadNav.tsx": () => import("../components/mockups/navbar/OldTigersHeadNav.tsx")
};
